### ISSUE TITLE
GK4 vs. GK5

### ISSUE THREAD

**Issue by kiliankoe** [juliuste/gauss-krueger#1]
Hi,

I'm not quite sure if this is the correct place to ask 😕 
I'm having an issue where I'm trying to convert a WGS84 coordinate to GK4. Here's a minimal code example.

```js
const gk = require('gauss-krueger')

let wgs = {'lat': 51.031658, 'lon': 13.727130}
console.log(gk.wgs2gk(wgs)) // { x: 5410847, y: 5655930 }
```

The problem with the given output is that the GK coordinate is GK5 and not GK4. Unfortunately I specifically need a GK4 coordinate for my use-case. 
Any help with this would be much appreciated! I really don't have much of a clue about coordinate systems and my (questionable) knowledge is based on tiny fragments pulled together from a selection of sources 😁

**Comment by derhuerst** [comment]
bump. (:

**Comment by juliuste** [comment]
Sorry for the long response time, I'm quite busy at the moment. You will get your answer this later this week if that is ok for you?

**Comment by kiliankoe** [comment]
Sure! And thanks! 😊

**Comment by kiliankoe** [comment]
Hey again, sorry for bringing this topic back up 🙈 Finally got back around to working on a project of mine (an api wrapper for the local public transport provider - VVO). They expect GK4 coordinates and GK4 coordinates only despite being in a GK5 zone according to this lib. Otherwise their server just errors out 😕

**Comment by juliuste** [comment]
LOL. Sorry for the ridiculous delay. I rewrote the entire module tonight (it uses the brilliant `proj4` library now), "custom" GK zones are finally also supported.

```js
const gk = require('gauss-krueger')
const forcedGK4 = gk.toWGS(coordinates, 4)
```

I hope this is helpful. One last side note: Keep in mind that this module uses the **Bessel** ellipsoid since this was the most commonly used ellipsoid in Germany. Saxony has been mostly using the **Krasovsky** ellipsoid until 2014 though. (Just in case this might be relevant for you, living in Dresden afaik?)

**Comment by juliuste** [comment]
Assuming your data is in [`EPSG:3398`](http://spatialreference.org/ref/epsg/rd83-gauss-kruger-zone-4/), which is/was used in Saxony, you could do this:

```js
const proj4 = require('proj4')
const epsg = require('epsg')

// GK4 to WGS84
let gkCoordinates = {x: 4000000, y: 6000000}
let wgsCoordinates = proj4(epsg['EPSG:3398'], 'WGS84', inputCoordinates) // {x: longitude, y: latitude}

// WGS84 to GK4
wgsCoordinates = {x: 13.4, y: 52.5} // x for longitude and y for latitude
gkCoordinates = proj4('WGS84', epsg['EPSG:3398'], inputCoordinates)
```

**Comment by kiliankoe** [comment]
Oh no, a proj-dependent rewrite is awesome for this repo, but unfortunately doesn't help me 🙈 My api wrapper is written in Swift and I just translated the original code here to a [small Swift package](https://github.com/kiliankoe/gausskrueger) and was hoping to somehow figure out how to _adjust_ the calculation to spit out GK5 coords, not really understanding any of the geomath happening 🙈😄 

Would love to use proj4 myself, but I'm running into a few compiletime issues on that front. Looks like I'll be spending some more time trying to figure that out. 

Thanks anyway though! Especially for the few additional bits of info regarding data formats and ellipsoids! 😊
